# Generated by Django 5.2.7 on 2025-10-22 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('device', models.IntegerField(null=True)),
                ('sector', models.IntegerField(blank=True, null=True)),
                ('irrigating', models.BooleanField(default=False)),
                ('failure', models.BooleanField(default=False)),
                ('coordinates', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='crops.crop')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='maps.map')),
            ],
        ),
    ]
