# Generated by Django 5.2.7 on 2025-10-22 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_num', models.IntegerField(null=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('connected', models.BooleanField(default=False)),
                ('failure', models.BooleanField(default=False)),
                ('irrigating', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, related_name='devices', to='areas.area')),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='maps.map')),
            ],
        ),
    ]
