# Generated by Django 5.2.7 on 2025-10-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='areas',
        ),
    ]
